//GENERATED BY go-create
package main

import (
	"log"

	gen "github.com/Seifbarouni/go-config-server/internal"
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	gen.GenerateRoutes(app)

	log.Fatal(app.Listen(":3001"))
}
